// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.20.3
// source: PieFireDire.proto

package services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BeefRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BeefRequest) Reset() {
	*x = BeefRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PieFireDire_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeefRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeefRequest) ProtoMessage() {}

func (x *BeefRequest) ProtoReflect() protoreflect.Message {
	mi := &file_PieFireDire_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeefRequest.ProtoReflect.Descriptor instead.
func (*BeefRequest) Descriptor() ([]byte, []int) {
	return file_PieFireDire_proto_rawDescGZIP(), []int{0}
}

type BeefResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Beef *Beef `protobuf:"bytes,1,opt,name=beef,proto3" json:"beef,omitempty"`
}

func (x *BeefResponse) Reset() {
	*x = BeefResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PieFireDire_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BeefResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeefResponse) ProtoMessage() {}

func (x *BeefResponse) ProtoReflect() protoreflect.Message {
	mi := &file_PieFireDire_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeefResponse.ProtoReflect.Descriptor instead.
func (*BeefResponse) Descriptor() ([]byte, []int) {
	return file_PieFireDire_proto_rawDescGZIP(), []int{1}
}

func (x *BeefResponse) GetBeef() *Beef {
	if x != nil {
		return x.Beef
	}
	return nil
}

type Beef struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TBone    int32 `protobuf:"varint,1,opt,name=t-bone,json=tBone,proto3" json:"t-bone,omitempty"`
	Fatback  int32 `protobuf:"varint,2,opt,name=fatback,proto3" json:"fatback,omitempty"`
	Pastrami int32 `protobuf:"varint,3,opt,name=pastrami,proto3" json:"pastrami,omitempty"`
	Pork     int32 `protobuf:"varint,4,opt,name=pork,proto3" json:"pork,omitempty"`
	Meatloaf int32 `protobuf:"varint,5,opt,name=meatloaf,proto3" json:"meatloaf,omitempty"`
	Jowl     int32 `protobuf:"varint,6,opt,name=jowl,proto3" json:"jowl,omitempty"`
	Enim     int32 `protobuf:"varint,7,opt,name=enim,proto3" json:"enim,omitempty"`
	Bresaola int32 `protobuf:"varint,8,opt,name=bresaola,proto3" json:"bresaola,omitempty"`
}

func (x *Beef) Reset() {
	*x = Beef{}
	if protoimpl.UnsafeEnabled {
		mi := &file_PieFireDire_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Beef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Beef) ProtoMessage() {}

func (x *Beef) ProtoReflect() protoreflect.Message {
	mi := &file_PieFireDire_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Beef.ProtoReflect.Descriptor instead.
func (*Beef) Descriptor() ([]byte, []int) {
	return file_PieFireDire_proto_rawDescGZIP(), []int{2}
}

func (x *Beef) GetTBone() int32 {
	if x != nil {
		return x.TBone
	}
	return 0
}

func (x *Beef) GetFatback() int32 {
	if x != nil {
		return x.Fatback
	}
	return 0
}

func (x *Beef) GetPastrami() int32 {
	if x != nil {
		return x.Pastrami
	}
	return 0
}

func (x *Beef) GetPork() int32 {
	if x != nil {
		return x.Pork
	}
	return 0
}

func (x *Beef) GetMeatloaf() int32 {
	if x != nil {
		return x.Meatloaf
	}
	return 0
}

func (x *Beef) GetJowl() int32 {
	if x != nil {
		return x.Jowl
	}
	return 0
}

func (x *Beef) GetEnim() int32 {
	if x != nil {
		return x.Enim
	}
	return 0
}

func (x *Beef) GetBresaola() int32 {
	if x != nil {
		return x.Bresaola
	}
	return 0
}

var File_PieFireDire_proto protoreflect.FileDescriptor

var file_PieFireDire_proto_rawDesc = []byte{
	0x0a, 0x11, 0x50, 0x69, 0x65, 0x46, 0x69, 0x72, 0x65, 0x44, 0x69, 0x72, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x0d, 0x0a,
	0x0b, 0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x32, 0x0a, 0x0c,
	0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x04,
	0x62, 0x65, 0x65, 0x66, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x42, 0x65, 0x65, 0x66, 0x52, 0x04, 0x62, 0x65, 0x65, 0x66,
	0x22, 0xc7, 0x01, 0x0a, 0x04, 0x42, 0x65, 0x65, 0x66, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x5f, 0x62,
	0x6f, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x42, 0x6f, 0x6e, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x74, 0x62, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x66, 0x61, 0x74, 0x62, 0x61, 0x63, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x74, 0x72, 0x61, 0x6d, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x74, 0x72, 0x61, 0x6d, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x6b, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x6b, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65,
	0x61, 0x74, 0x6c, 0x6f, 0x61, 0x66, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x6d, 0x65,
	0x61, 0x74, 0x6c, 0x6f, 0x61, 0x66, 0x12, 0x12, 0x0a, 0x04, 0x6a, 0x6f, 0x77, 0x6c, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6a, 0x6f, 0x77, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x6e,
	0x69, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x65, 0x6e, 0x69, 0x6d, 0x12, 0x1a,
	0x0a, 0x08, 0x62, 0x72, 0x65, 0x73, 0x61, 0x6f, 0x6c, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x62, 0x72, 0x65, 0x73, 0x61, 0x6f, 0x6c, 0x61, 0x32, 0x47, 0x0a, 0x0b, 0x50, 0x69,
	0x65, 0x46, 0x69, 0x72, 0x65, 0x44, 0x69, 0x72, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x53, 0x75, 0x6d,
	0x6d, 0x61, 0x72, 0x79, 0x12, 0x15, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x42, 0x65, 0x65, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_PieFireDire_proto_rawDescOnce sync.Once
	file_PieFireDire_proto_rawDescData = file_PieFireDire_proto_rawDesc
)

func file_PieFireDire_proto_rawDescGZIP() []byte {
	file_PieFireDire_proto_rawDescOnce.Do(func() {
		file_PieFireDire_proto_rawDescData = protoimpl.X.CompressGZIP(file_PieFireDire_proto_rawDescData)
	})
	return file_PieFireDire_proto_rawDescData
}

var file_PieFireDire_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_PieFireDire_proto_goTypes = []interface{}{
	(*BeefRequest)(nil),  // 0: services.BeefRequest
	(*BeefResponse)(nil), // 1: services.BeefResponse
	(*Beef)(nil),         // 2: services.Beef
}
var file_PieFireDire_proto_depIdxs = []int32{
	2, // 0: services.BeefResponse.beef:type_name -> services.Beef
	0, // 1: services.PieFireDire.Summary:input_type -> services.BeefRequest
	1, // 2: services.PieFireDire.Summary:output_type -> services.BeefResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_PieFireDire_proto_init() }
func file_PieFireDire_proto_init() {
	if File_PieFireDire_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_PieFireDire_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeefRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PieFireDire_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BeefResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_PieFireDire_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Beef); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_PieFireDire_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_PieFireDire_proto_goTypes,
		DependencyIndexes: file_PieFireDire_proto_depIdxs,
		MessageInfos:      file_PieFireDire_proto_msgTypes,
	}.Build()
	File_PieFireDire_proto = out.File
	file_PieFireDire_proto_rawDesc = nil
	file_PieFireDire_proto_goTypes = nil
	file_PieFireDire_proto_depIdxs = nil
}
